### ISSUE TITLE
Upside down tabs are broken in Kdenlive

### ISSUE THREAD

**Issue by ludovitkramar** [Luwx/Lightly#40] opened 2021-01-04 04:15 UTC
![Screenshot_20210104_121456](https://user-images.githubusercontent.com/61901244/103500603-76edbf80-4e43-11eb-93ce-ffb12bf8dce7.png)

**Comment by ludovitkramar** [comment] 2021-01-04 04:16
r2066.287151b6-1 from AUR in arch linux

**Comment by 4VRDriver** [comment] 2021-01-04 14:32
Duplicate of https://github.com/Luwx/Lightly/issues/35

**Comment by Luwx** [comment] 2021-02-03 07:44
Done in 23db28a87053b2cf7ec2eae3b11c70fe5fc0ff57 .

**Closed by Luwx** 2021-02-03 07:44 UTC
