### ISSUE TITLE
Editing the lightly window decoration settings don't work

### ISSUE THREAD

**Issue by RGBCube** [Luwx/Lightly#197] opened 2022-11-09 06:23 UTC
this button doesn't make anything pop up, but it works fine for the builtin themes:
![img](https://i.ibb.co/1Qgkt7T/IMG-09-11-2022-09-20-19.png)

**Comment by boehs** [comment] 2022-11-16 02:54
Duplicate of #189, resolved in #177

**Comment by boehs** [comment] 2023-01-10 21:23
Consider closing this issue if you agree it's a duplicate

**Closed as completed** 2023-01-11 05:25 UTC
