### ISSUE TITLE
Doesn't work at Debian #2 // KWindowShadow missing

### ISSUE THREAD

**Issue by Stefcan261** [Luwx/Lightly#119] opened 2021-07-23 14:34 UTC
Hello,
i had a lot of problems (debian needs experimental "extra-cmake-modules" version 5.66 or higher) but made it to installation process. installation via zypper wasn't working at all so i had to do
manual installation:
make

[ 31%] Built target lightly_autogen
[ 32%] Building CXX object kstyle/CMakeFiles/lightly.dir/lightlyblurhelper.cpp.o
In file included from /home/dings/Lightly/kstyle/lightlyhelper.h:29,
                 from /home/dings/Lightly/kstyle/lightlyblurhelper.h:35,
                 from /home/dings/Lightly/kstyle/lightlyblurhelper.cpp:31:
/home/dings/Lightly/kstyle/lightlyshadowhelper.h:26:10: fatal error: KWindowShadow: No such file or directory
 #include <KWindowShadow>
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [kstyle/CMakeFiles/lightly.dir/build.make:422: kstyle/CMakeFiles/lightly.dir/lightlyblurhelper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:716: kstyle/CMakeFiles/lightly.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

am i missing something or is it missing in the current build?

**Comment by D3SOX** [comment] 2021-07-23 14:35
Duplicate of #113 #83 #31 #116

**Comment by ThePythonicProgrammer** [comment] 2021-08-17 00:28
Debian 10 seems to be missing the latest version of several lightly dependencies. When I upgraded to Debian Unstable, lightly installed perfectly fine.

**Comment by Luwx** [comment] 2021-11-14 03:25
Should be fixed.

**Closed by Luwx** 2021-11-14 03:25 UTC
