### ISSUE TITLE
The bar show Space Information in Dolphin became a blurred box

### ISSUE THREAD

**Issue by vuongtuha** [Luwx/Lightly#150] opened 2022-01-14 03:12 UTC
I tried to reset config in Application Style to default, but this ugly box still appears. Hope anyone guides me re-config
![Screenshot_20220114_095029](https://user-images.githubusercontent.com/70053986/149445213-678d8ada-ae32-42cd-bc4d-08d49cfba967.png)

**Comment by Cognitohazard** [comment] 2022-01-16 20:45
Have this problem too.

**Comment by nisiddharth** [comment] 2022-01-31 05:35
This is same as #69

**Comment by Luwx** [comment] 2022-04-13 21:14
Duplicate of https://github.com/Luwx/Lightly/issues/69

**Closed by Luwx** 2022-04-13 21:14 UTC
