### ISSUE TITLE
Irregular opacity

### ISSUE THREAD

**Issue by Dimoniux** [Luwx/Lightly#7] opened 2020-08-24 16:01 UTC
Hi, your job is amazing. I would like to share you some problems I noticed. As you can see in the screenshots the tooltipbar does not follow color/ blur of window and also the titlebar wen window is not focused, the "material style" is not in all the system and ther are some problems. 
Thank you a lot.

![Screenshot_20200819_102313](https://user-images.githubusercontent.com/70139450/91067631-780c1600-e633-11ea-8d40-01c01db66f03.png)
![Screenshot_20200824_174243](https://user-images.githubusercontent.com/70139450/91067668-82c6ab00-e633-11ea-9dd3-767ac599649d.png)

**Comment by Luwx** [comment] 2020-08-27 02:11
Thanks for the feedback!

So, the bugs I see in the screenshots:

* _Titlebar color doesn't match the window background_. This is most likely caused by the color scheme. Make sure that both ```inactiveBackground``` and ```inactiveBackground``` in [WM] are the same.

* _Menubar with different color_. I believe it's fixed in the latest commits.

* _Plasma settings windows have no blur_. It's intentionally disabled for now, it may cause some issues. 

* _The "remove" button with drop down arrow looks weird_. Yes, I'm yet to fix this.

I'm closing this. Feel free to open an issue to track the drop down button specifically until it is fixed.

**Closed by Luwx** 2020-08-27 02:11 UTC
