### ISSUE TITLE
Doesn't work at Debian

### ISSUE THREAD

**Issue by Redon02** [Luwx/Lightly#115] opened 2021-07-15 18:33 UTC
Hi
I want to install Lightly, but I can't.
I go to manual instalation, install for Ubuntu (I think the Ubuntu is simillar to Debian), and next to I make "Build and install" (I install git-man and cmake), everythink was okay, but I am stoping at this line "cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF .."
Terminal shows me error. What I can do?

**Comment by UltraBlackLinux** [comment] 2021-07-19 19:56
interesting logs

**Comment by D3SOX** [comment] 2021-07-23 14:36
Possibly a duplicate of #113 #83 #31 #116 #115
> Terminal shows me error

Provide the exact output.

**Closed** 2021-11-14 03:31 UTC
